### ISSUE TITLE
template for reaching out to universities

### ISSUE THREAD

**Issue by ashleygwilliams** [rustbridge/team#10]
would love to have a template for helping reach out to universities to see if they would co sponsor an event at their campus!

**Comment by ghost** [comment]
@ashleygwilliams If you want to set up a basic structure, I can help flesh out some of the details!

**Comment by ashleygwilliams** [comment]
guh, just seeing this @oe - travel stuff has me a bit behind. i was generally thinking:

- hello
- who we are
- why rust + bridge programs are a great combo
- history with universities (hackillinois, CUSEC, rustbridge waterloo)
- workshop details (how long, how many, who teaches?, etc)
- thanks so much, hope to hear from u soon

**Comment by ghost** [comment]
@ashleygwilliams i can probably work with that - i'll write a basic outline after the meeting
