### ISSUE TITLE
14 march 2018: agenda

### ISSUE THREAD

**Issue by ashleygwilliams** [rustbridge/team#13]
- Introductions!
- Upcoming Events
   - RustBridge Boston (@nikomatsakis)
   - RustBridge Waterloo (@arshiamufti)
   - RustBridge Nairobi https://twitter.com/RustNairobi/status/973937947111251968
   - Online Teacher Training (@ashleygwilliams)
   - RustFest (@ashleygwilliams + ????)
   - RustConf (@ashleygwilliams + ????)
- On-going Projects
   - In-A-Box,
     - university outreach https://github.com/rustbridge/team/issues/10
   - Website
   - WRITE DOWN THE CURRICULUM (@ashleygwilliams, this is me yelling at myself)
- Safety Discussion re Waterloo event

**Comment by nikomatsakis** [comment]
I am reminded -- I'd like to get some "standard RustBridge copy" for using in e-mails etc
