### ISSUE TITLE
meeting agenda: 11 Apr 2018

### ISSUE THREAD

**Issue by ashleygwilliams** [rustbridge/team#16]
- waterloo recap
- all hands recap
- what do we want to work on for Q2

**Comment by ghost** [comment]
can we get a little coordination wrt the rustbridge europe thing in there too?

**Comment by ashleygwilliams** [comment]
goals for Q2:
- get doc team involved re: lesson plan modules around specific docs (e.g. rust by example)
- do 3 events
    - boston
    - paris
    - ???
- ship the new site and start leveraging it for future events
- ship the in-a-box repo
- build rust-koans replacement for exercism module

**Comment by arshiamufti** [comment]
do we want to move the Q2 goals to the repository?
