### ISSUE TITLE
RustBridge India

### ISSUE THREAD

**Issue by ashleygwilliams** [rustbridge/team#2]
- chat scheduled for Tuesday 16 Jan 2018

**Comment by exagil** [comment]
Hey @ashleygwilliams, would you be holding this session in India?

**Comment by ashleygwilliams** [comment]
@chi6rag yes! the plan is to host an event in India. we haven't had the kick off meeting yet but watch this issue and i'll be updating it with more information :)

**Comment by exagil** [comment]
Awesome! 👍

**Comment by ashleygwilliams** [comment]
closing as this no longer seems to have a champion. would love to reopen if someone would like to volunteer to help organize!
