### ISSUE TITLE
RustBridge team meeting: 06 June 2018

### ISSUE THREAD

**Issue by ghost** [rustbridge/team#20]
## Invited

@rustbridge/all, @rahul-thakoor

## Agenda

- RustBridge Paris update (@ashleygwilliams, @oe)

**Comment by rahul-thakoor** [comment]
Thanks!

**Comment by ghost** [comment]
@rahul-thakoor Just in case, the join link is: http://appear.in/rustaceans

**Comment by ghost** [comment]
@rahul-thakoor totally forgot that we have a guide for organizing RustBridge events written up here too: https://rustbridge.github.io/hello/organizing/
