### ISSUE TITLE
 RustBridge Hyderabad

### ISSUE THREAD

**Issue by ranjithrajv** [rustbridge/team#28]
Dates: November 2, 3, 2018
Venue: Mahindra École Centrale, Hyderabad(Zero charges for Venue)
Participation count: Around 500+ students

Projector: Available
Internet Connection: Available
Electricity (multiplier cables): Available

Support Needed:

*  Mentors/Speakers
*  Budget
*  Swag

**Comment by ghost** [comment]
Thanks for informing us! Do you already have any set curriculum? I'm noticing you're planning for 2 days, are you sure this will pan out given that our curriculum and event structure are usually meant to be one day only?

What kind of support do you need mentor-wise? This is unfortunately a bit short-notice to have anyone fly out to your location, and I'm not sure there's much we can do to help you find local mentors beyond a shout-out on Twitter.

I'd also love more information regarding your budget and what kind of swag you need.

**Comment by ranjithrajv** [comment]
Curriculum is not yet finalized completely, but we are considering [Rust Book](https://doc.rust-lang.org/book/2018-edition/) and [Rust by example](https://doc.rust-lang.org/stable/rust-by-example/) as of now. We are planning talks/sessions on 1 day and another day with hands-on workshop along with hackathon on our community project [Rust for Undergrads](https://github.com/rustindia/Rust-for-undergrads)

Thanks for offering for shout-out on twitter, can you support travel if any speaker/mentor agrees to come to the event? 

Swag could be T-shirts, stickers, buttons and Handouts/Books on Rust to gift to students, and budget requirements for banners/posters, local transport and logistics, food/drinks for participants, I'll share the detailed budget if you can provide with any template if you have.

**Comment by ghost** [comment]
It seems like the event you're planning is not a RustBridge, but rather a conference with something vaguely resembling a RustBridge thrown in. We generally require a 2-3 months notice, and for an event of this size, at least half a year.

We also ask that you refrain from using the RustBridge name for your event in its current state.
