### ISSUE TITLE
RustBridge at RustFest Rome

### ISSUE THREAD

**Issue by ghost** [rustbridge/team#29]
## Summary 📃

RustBridge event happening in accord with RustFest Rome (https://rome.rustfest.eu). Location provided by RustFest.

## Details

- *Date*  🕐: Sunday, November 25th
- *Venue* 🏠: Centro Congressi Frentani, Rome, Italy
- *Maximum Venue Size*: ~90
- *Signup Form* 📝: To be provided
- *Airtable Link* 🛩: https://airtable.com/tblZRU52m75vv9PfL (_for organizers only_)

## Volunteer as Teacher or TA!

First off, thanks for volunteering! Please contact us via our Rust Team Discord channel (`#rustbridge` on https://discord.gg/rust-lang), or write me an email at `olivia at fastmail dot org`, and we'll talk details.

**Comment by ashleygwilliams** [comment]
I plan on attending and would be happy to teach or co-teach.
