### ISSUE TITLE
RustBridge Cleveland: 5th October 2019

### ISSUE THREAD

**Issue by jonknapp** [rustbridge/team#33]
- Coaches: Heather F, Stewart W, @jonknapp
- Venue: [TechHive](https://www.digitalc.org/midtown-tech-hive)
- Date: October 5th, 2019
- Anything needed?: nope! unless the RustBridge logo is available to use in vector form

We just locked down a location, though we've been talking through the content and approach for a month or so. We'll be reaching out to local companies for sponsorship soon to cover venue and food costs.

I'd like to get some stickers printed for the event unless there is official swag available. I was going to base a design on the RustBridge bridge/Ferris logo with "RustBridge Cleveland" or something in text. We will probably only need ~30 stickers though we haven't started to officially find attendees.

**Comment by manyinsects** [comment]
Sorry for the extremely late response, GitHub is not currently being nice to me. We'll be getting a new project logo soon, but probably after your workshop. Do you still need other swag? The community team can probably help you out with that.

**Comment by jonknapp** [comment]
Quite alright. I ended up making a vector of the original logo and adding our city name under it for a pretty cool attempt at a sticker. No other swag needed for now unless you think there'd be something fun for attendees.

![sticker](https://user-images.githubusercontent.com/8836231/65252610-46a3d580-dac7-11e9-9a93-5886f6dad38c.png)

**Comment by manyinsects** [comment]
@jonknapp Ooh, do you have that vector still? I don't actually have a high resolution version of our logo.

**Comment by jonknapp** [comment]
Yep, it's not the best recreation, but it worked for my needs.

[rustbridge logo.zip](https://github.com/rustbridge/team/files/3631709/rustbridge.logo.zip)
